[package]
name = "module1"
version = "0.1.0"
edition = "2024"

[dependencies]
flawless = "1.0.0-beta.3"
flawless-http = "1.0.0-beta.3"
flawless-utils = "1.0.0-beta.3"
log = "0.4.28"
serde = { version = "1.0", features = ["derive"] }
