[package]
name = "tutorial-verify"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
notify = "6"
notify-debouncer-mini = "0.4"
nu-ansi-term = "0.50"